app/urls.py
from django.contrib import admin
from django.urls import path, include
from cronometro import views

urlpatterns = [
    #path('', views.homeView, name='home'),  # Ruta raíz que llama a la función homeView
    path('admin/', admin.site.urls),
    path('', include('cronometro.urls')),
    
    
]

cronometro/urls.py
from django.urls import path, re_path
from .views import *

app_name = "cronometro"

urlpatterns = [
    path('', homeView, name='home'),
    path('login/', login, name = 'login'),
    path('logout/', logout, name = 'logout'),
    
    #recuperacion
    path('inicio_recuperar/', inicioRecuperacion, name = 'inicioRecuperacion'),
    path('correo/', correoRecuperacion, name = 'correoRecuperacion'),
    path('cronometro/recuperar/', recuperar, name = 'recuperar'),
    path('restablecer_contrasena/<int:id>', formRestablecerContrasena, name = 'formRestablecerContrasena'),
    
    #Usuario
    path('registro/', registro, name = 'registro'),
    path('save/', guardarUsuario, name = 'guardarUsuario'),
    path('list_usuario/', listarUsuarios, name='listarUsuarios'),
    path('edit_usuario/<int:id>', actualizarUsuario, name='actualizarUsuario'),
    path('edicion_usuario/', edicionUsuario, name='edicionUsuario'),
    path('estado_usuario/<int:id>', deshabilitarUsuario, name='deshabilitarUsuario'),
    
    
    #Cronometro
    path('cronometro/', cronometroView, name= 'cronometro'),
    path('selecOper/', selecOperario, name= 'selecOperario'),
    path('cronometro/cronometro/tiempo_parcial/', tiempo_parcial, name='tiempo-parcial'),
    path('cronometro/guardarTiempoEstandar/<int:id>',guardarTiempoEstandar , name= 'guardarTiempoEstandar'),
    path('cronometro/base/', base, name='base'),
    #operario
    path('operario/', crearOperario, name='crearOperario'),
    path('save_operario/', guardarOperario, name='guardarOperario'),
    path('mod_operario/', guardarTiempoParcial, name='guardarTiempoParcial'),
    path('list_operario/', listarOperarios, name='listarOperarios'),
    path('edit_operario/<int:id>', actualizarOperario, name='actualizarOperario'),
    path('edicion_operario/>', edicionOperario, name='edicionOperario'),
    path('estado_operario/<int:id>', deshabilitarOperario, name='deshabilitarOperario'),
    path('operario/historico/<int:id>', historial, name='historial'),
    path('operario/eliminar_historia/<int:id>', eliminarHistoria, name='eliminarHistoria'),
    
    #Maquina
    path('maquina/', crearMaquina, name='crearMaquina'),
    path('save_maquina/', guardarMaquina, name='guardarMaquina'),
    path('list_maquina/', listarMaquinas, name='listarMaquinas'),
    path('estado_maquina/<int:id>', deshabilitarMaquina, name='deshabilitarMaquina'),
    path('edit_maquina/<int:id>', actualizarMaquina, name='actualizarMaquina'),
    path('edicion_maquina/<int:id>', editarMaquina, name='editarMaquina'),
    
    #Operacion
    path('operacion/', crearOperacion, name='crearOperacion'),
    path('save_operacion/', guardarOperacion, name='guardarOperacion'),
    path('list_operacion/', listarOperaciones, name='listarOperaciones'),
    path('estado_operacion/<int:id>', deshabilitarOperacion, name='deshabilitarOperacion'),
    path('edit_operacion/<int:id>', actualizarOperacion, name='actualizarOperacion'),
    path('edicion_operacion/>', editarOperacion, name='editarOperacion'),
    
    #Empresa
    path('crear_empresa/', crearEmpresa, name='crearEmpresa'),
    path('guardar_empresa/', guardarEmpresa, name='guardarEmpresa'),
    path('listar_empresa/', listarEmpresa, name='listarEmpresa'),
    path('actualizar_empresa/<int:id>', actualizarEmpresa, name='actualizarEmpresa'),
    path('guardar_ac_empresa/<int:id>', guardarAcEmpresa, name='guardarAcEmpresa'),
    path('estado_empresa/<int:id>', estadoEmpresa, name='estadoEmpresa'),
    
    #informe
    path('cronometro/generar_informe_operario/<int:id>', generarInforme, name='generarInforme'),
    path('buscar_operario/', buscarOperario, name='buscarOperario'),
    
    re_path(r'^.*/$', redireccionar_a_inicio),
    
]

cronometro/models.py
from django.db import models
from datetime import date
from email.policy import default
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Empresa(models.Model):
    nombre = models.CharField(max_length=50)
    estado = models.BooleanField(default=True)
    nit = models.DecimalField(max_digits=10, decimal_places=0)
    
class Usuario(AbstractUser):
    idEmpresa = models.ForeignKey(Empresa, on_delete=models.DO_NOTHING, null=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, unique = True)
    clave = models.CharField(max_length=254)
    roles_CHOISES = (('A', 'Administrador'), ('U', 'Usuario'))
    rol = models.CharField(max_length=20, choices=roles_CHOISES, default='U')
    fecha_nacimiento = models.DateField(default=date.today)
    estado = models.BooleanField(default=False)
    
     # Agregue related_name para resolver el conflicto
    groups = models.ManyToManyField(
        'auth.Group', related_name='usuario_set', blank=True
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission', related_name='usuario_set', blank=True
    )
    
    def __str__(self) -> str:
        return f"{self.nombre}"
    
class Operario(models.Model):
    idEmpresa= models.ForeignKey(Empresa, on_delete=models.DO_NOTHING, null=True)
    nombre = models.CharField(max_length=50)
   
    email = models.EmailField(max_length=100, unique = True)
    #tiemposMiliseg = models.BinaryField(blank=True, null=True)
    #tiemposNormales =models.BinaryField(blank=True, null=True) 
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    estado = models.BooleanField(default=True)
    
    def __str__(self) -> str:
        return f"{self.nombre}"
    

    
class Maquina(models.Model):
    idEmpresa = models.ForeignKey(Empresa, on_delete=models.DO_NOTHING, null=True)
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    estado = models.BooleanField(default=True)    

class Operacion (models.Model):
    idEmpresa = models.ForeignKey(Empresa, on_delete=models.DO_NOTHING, null=True)
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    estado = models.BooleanField(default=True)
    
class OperacionOperario(models.Model):
    
    idOperario = models.ForeignKey(Operario, on_delete=models.DO_NOTHING, null=True)
    idOperacion = models.ForeignKey(Operacion, on_delete=models.DO_NOTHING)
    idMaquinas = models.ForeignKey(Maquina, on_delete=models.DO_NOTHING)
    fechas = models.DateTimeField(auto_now_add=True, blank=True)
    tiempoEstandar = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    factorRitmo = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    uniHoras = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    escalaSuplementos = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    estado = models.BooleanField(default=True)
    
    def __str__(self):
        return f"id: {self.id} - Fr {self.factorRitmo} - Es {self.escalaSuplementos}"
    
    

cronometro/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import *
from django.db.models import Q
# Mensajes tipo cookies temporales
from django.contrib import messages
from django import forms
# Gestión de errores de base de datos
from django.db import IntegrityError  
# Paginador
from django.core.paginator import Paginator 
import json 
from django.core.serializers.json import DjangoJSONEncoder
# recuperacion de contraseña
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.shortcuts import get_object_or_404

from django.core.mail import send_mail
from django.conf import settings
#informe operario excel

from openpyxl import Workbook
import pytz
from django.utils import timezone

#Libreria para encripación
from passlib.context import CryptContext
# Round: Iteraciones para reducir la posibilidad de cracking.
contexto = CryptContext(
    schemes=["pbkdf2_sha256"],
    default="pbkdf2_sha256",
    pbkdf2_sha256__default_rounds=333
)


# Create your views here.



def homeView(request):
    """
    Renderiza la vista de inicio.

    Argumentos:
        solicitud (HttpRequest): el objeto de solicitud HTTP.
    
    Devoluciones:
        HttpResponse: la respuesta HTML representada.
    """
    return render(request,'cronometro/index.html')

def homeView2(request):
    return render(request,'cronometro/base/base2.html')

def selecOperario (request):
    """
        Representa la plantilla 'selec_operario.html' con la solicitud dada.

        Parámetros:
            solicitud (HttpRequest): el objeto de solicitud HTTP.
        
        Devoluciones:
            HttpResponse: el objeto de respuesta HTTP.
        """
    login = request.session.get('logueoUsuario', False)
    if Usuario.objects.get(id = login[0]).estado == True:
        
        
        operarios = Operario.objects.filter(idEmpresa=login[5]).filter(estado=True)
        maquinas = Maquina.objects.filter(idEmpresa=login[5]).filter(estado=True)
        operaciones = Operacion.objects.filter(idEmpresa=login[5]).filter(estado=True)
        
        #datos_json = json.dumps(list(datos), cls=DjangoJSONEncoder)
        #return render(request, 'cronometro/operario/selec_operario.html', {
        #   'datos_json': datos_json,
        #  'operarios' : operarios
        #})
            
        return render(request,'cronometro/operario/selec_operario.html', {'operarios' : operarios , 'maquinas' : maquinas , 'operaciones' : operaciones})
    else:
        messages.warning(request, "Inicie sesión o solicite activación")
        return redirect('cronometro:home')

def login (request):
    """
    Esta función es responsable de manejar la solicitud de inicio de sesión.

    Argumentos:
        solicitud (HttpRequest): el objeto de solicitud HTTP.

    Devoluciones:
        HttpResponseRedirect: una respuesta de redireccionamiento a la página de inicio.

    Sube:
        Usuario.DoesNotExist: Si el usuario no existe.
    """
    if request.method == "POST":
        try:
            
            email = request.POST['email']
            clavePost = request.POST['clave']
            clave= contexto.hash(clavePost)       
            usuario = Usuario.objects.get(email = email)
            
            if contexto.verify(clavePost, usuario.clave):
                request.session["logueoUsuario"] = [usuario.id, usuario.nombre, usuario.apellido, usuario.email, usuario.get_rol_display(), usuario.idEmpresa.id, usuario.idEmpresa.nombre]       
                # -------------
                messages.success(request, "Bienvenido")
            else:
                messages.warning(request, "Contraseña incorrecta")
                
            return redirect('cronometro:home')
        except Usuario.DoesNotExist:
            messages.warning(request, "El usuario no existe")
            return redirect('cronometro:home')
        except Exception as e:
            
            if str(e) == "'NoneType' object has no attribute 'id'":
            # Mostrar otro mensaje cuando se produce el error 'NoneType' object has no attribute 'id'
                messages.error(request, "Comuniquese con el administrador para habilitar su cuenta y adjuntar a una empresa")
            else:
            # Mostrar el mensaje de error original
                messages.error(request, f"Error: {e}")
            
            return redirect('cronometro:home')
    else:
        messages.warning(request, "Usted no ha enviado datos")
        return redirect('cronometro:home')
    
def registro(request):
    
    try:
        
        return render(request, 'cronometro/usuario/registro_usuario.html' )
    
        
        return redirect('cronometro:home')
    except Exception as e:
        messages.error(request, f"Error: {e}")
        return redirect('cronometro:home')
        
        
    
    

def guardarUsuario(request):
    """
    Guarda un usuario en la base de datos.
    Parameters:
    request (HttpRequest): La solicitud HTTP recibida.
    Returns:
    HttpResponseRedirect: Redirige al usuario hacia la página home si el usuario se guarda correctamente.
    """
    
    try: 
        if request.method == "POST":
            
            usuario = Usuario(
                email= request.POST['email'],
                nombre= request.POST['nombre'],
                apellido= request.POST['apellido'],
                fecha_nacimiento=request.POST['fecha_nacimiento'],
                clave = contexto.hash(request.POST['clave']) ,
                password= contexto.hash(request.POST['clave']),
                username= request.POST['email'],
                estado=False
                
            )
            
            usuario.save()
            messages.success(request, f"El usuario  ha sido creado con éxito")
        
        else:
            messages.warning(request, "Usted no ha enviado datos")
    
    except Exception as e:
        
        messages.error(request, f"Error: {e}")
        return redirect('cronometro:registro')
        
    return redirect('cronometro:home')  


def inicioRecuperacion(request):
    return render(request, 'cronometro/usuario/inicio_recuperacion.html')

def correoRecuperacion(request):
    try:    
        if request.method == "POST":
            
            correo=  request.POST['correo'],
            correoV=  request.POST['correoV'],
            print(correo)
            print(correoV)
            
            if correo== correoV:
                usuario= Usuario.objects.get(email = request.POST['correo'])
                print(usuario.nombre)
                email= usuario.email
                
                token_generator = PasswordResetTokenGenerator()
                token = token_generator.make_token(usuario)
                # Almacena el token asociado con el usuario
                from django.contrib.sites.shortcuts import get_current_site

                request.session["usuarioR"] = [usuario.id]
                domain = get_current_site(request).domain
                mensaje = f'Haz clic en el siguiente enlace para restablecer tu contraseña: http://{domain}/cronometro/recuperar/?token={token}'
                #mensaje = f'Haz clic en el siguiente enlace para restablecer tu contraseña: http://127.0.0.1:8000/cronometro/recuperar/?token={token}'
                
                send_mail('Recuperación de contraseña', 
                          mensaje, 
                          settings.DEFAULT_FROM_EMAIL, 
                          [email],)
                
                messages.success(request, "Correo enviado")
                return redirect('cronometro:inicioRecuperacion')
            else:
                messages.warning(request, "Correo incorrecto")
                return redirect('cronometro:inicioRecuperacion')
        else:
            messages.warning(request, "Usted no ha enviado datos")
            return redirect('cronometro:inicioRecuperacion')
    except Exception as e:
        messages.error(request, f"Error: {e}")
        return redirect('cronometro:inicioRecuperacion')    
        
def recuperar(request):
    try:
        idUsuario = request.session.get('usuarioR')[0]
        
        print(idUsuario)
        token_generator = PasswordResetTokenGenerator()
        # Obtener el usuario correspondiente al token
        usuario = get_object_or_404(Usuario, pk=idUsuario)
        print(usuario)
        token = request.GET.get('token')
        print(token)

        # Validar el token
        if token_generator.check_token(usuario, token):
            # Token válido, permitir al usuario restablecer la contraseña
            # Mostrar un formulario para restablecer la contraseña
            messages.success(request, "Token válido")
            
            
            return render(request, 'cronometro/usuario/restablecer_contrasena.html', {'usuario': usuario})
        else:
            # Token inválido, mostrar un mensaje de error o redirigir a otra página
            # ...
            messages.warning(request, "Token inválido")
            return redirect('cronometro:inicioRecuperacion')
    except Usuario.DoesNotExist:
        # Handle the case when no Usuario object is found
        messages.warning(request, "Usuario no encontrado")
        return redirect('cronometro:inicioRecuperacion')
    
    except Exception as e:
        messages.error(request, f"Error: {e}")
        return redirect('cronometro:inicioRecuperacion')  

def formRestablecerContrasena(request, id):
    try:
        usuario = Usuario.objects.get(id = id)
        if request.method == "POST":
            
            clave = request.POST['password']
            claveV= request.POST['passwordV']
            
            if clave==claveV:
                usuario.clave = contexto.hash(clave)
                usuario.save()
                messages.success(request, "Contraseña actualizada")
            return redirect('cronometro:home')
    except Exception as e:

cronometro/templates/cronometro/usuario/edicion_usuario.html
{% extends 'cronometro/base/base.html' %}
{% load static %}

{% block titulo %}Inicio{% endblock titulo %}

{% block encabezado %}Bienbenido{% endblock encabezado %}
{% block subencabezado %}Index{% endblock subencabezado %}

{% block contenedor %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags != 'error' %}{{ message.tags }}{% elif message.tags == 'error' %}danger{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}

{% if request.session.logueoUsuario %}



<br>
<div class="contact-from-section mb-150">
    <div class="container text-center">
        <div class="formulario mx-auto">
            <div class="form-title">
                <h2>Edición de usuario</h2>
                
            </div>
            <form action="{% url 'cronometro:edicionUsuario' %}" class="needs-validation " novalidate="" method="post">
                {% csrf_token %}
                <input value="{{usuario.id}}" readonly name="id" type="hidden" required>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <p>Correo</p>
                        <input value="{{usuario.email}}" name="email" type="email" placeholder="" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <p>Nombres</p>
                        <input value="{{usuario.nombre}}" name="nombre" type="text" placeholder="Nombres" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <p>Apellidos</p>
                        <input value="{{usuario.apellido}}" name="apellido" type="text" placeholder="Apellidos" required>
                    </div>
                    <div class="form-group col-md-6 " style="text-align: center;" >
                        {% if request.session.logueoUsuario.3 == 'adm95193241@gmail.com' %}
                                    
                            <p style="margin-left: auto; margin-right: auto;">
                                <label for="idEmpresa">Empresa:</label>
                                <select id="idEmpresa" name="idEmpresa" class="form-control center" style="width: 200px;" required >
                                    
                                    {% for empresa in empresas %}
                                        <option value="{{empresa.id}}" {% if empresa.id == usuario.idEmpresa.id %} selected {% endif %}>{{empresa.nombre}}</option>                            
                                    {% endfor %}
                                </select>
                            </p>
                            {% else %}
                            <p>Empresa</p>
                                <input value="{{usuario.idEmpresa.nombre}}" name="empresa" type="text" readonly >
                            
                        {% endif %}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 ">
                        <br>
                        
                        <div class="d-flex justify-content-center">
                            {% if request.session.logueoUsuario.4 == 'Administrador' %}<!-- cambiar Rol -->
                                <p>Rol</p>
                                <div>
                                <select name="rol" class="form-control col-6" id="rol" title="Selecciona un rol" required>
                                    <option {% if usuario.rol == 'A' %} selected {% endif %} value="A">Administrador</option>
                                    <option {% if usuario.rol == 'U' %} selected {% endif %} value="U">Usuario</option>
                                </select>
                                </div>
                            {%else%}
                                <p>Rol</p>
                                <input {% if usuario.rol == 'A' %} value="Administrador" {% else %} value="Usuario" {% endif %} name="rol" type="text" readonly>
                                
                                
                            {%endif%}
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <br>
                        <p>Fecha de nacimiento</p>
                        <input value="{{usuario.fecha_nacimiento|date:'Y-m-d'}}" name="fecha_nacimiento" type="date" required>
                    </div>
                
                    <div class="form-group col-md-2">
                        <div class="form-group col-md-6">
                            {% if request.session.logueoUsuario.4 == 'Administrador' %}
                            <br>
                            <label for="habilitadoUsuarios">Habilitado</label>
                            <br>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="radio" class="form-check-input" name="estado" {% if usuario.estado %} checked {% endif %} value="True" readonly>Sí
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <label class="form-check-label">
                                    <input type="radio" class="form-check-input" name="estado" {% if not usuario.estado %} checked {% endif %}value="False" readonly>No
                                </label>
                            </div>
                            {%else%}
                                <div class= "form-group col-md-4">
                                    <span> Estado </span>
                                    <input type="text" {% if usuario.estado == True %} value="Activo" placeholder="Habilitado" {% else %} value="Deshabilitado" placeholder="Deshabilitado" {% endif %} name="estado"  type="text" readonly>
                                </div>
                            {%endif%}

                            


                        </div>
                    </div>
                </div>
                <br/>
                <!-- Botón del enviar formulario-->
                <div class="form-btns">
                    <button type="submit">Enviar formulario</button>
                    <button type="reset">Limpiar formulario</button>
                </div>
            </form>
        </div>
    </div>
</div>



{% else %}
No hay datos.
Inicie sesion.
{% endif %}


{% endblock contenedor %}

cronometro/templates/cronometro/usuario/inicio_recuperacion.html
{% extends 'cronometro/base/base.html' %}
{% load static %}

{% block titulo %}Recuperación de contraseña{% endblock titulo %}

{% block encabezado %}Bienbenido{% endblock encabezado %}
{% block subencabezado %}Index{% endblock subencabezado %}

{% block contenedor %}

{% if messages %}
        {% for message in messages %}
            <div class="alert alert-{% if message.tags != 'error' %}{{ message.tags }}{% elif message.tags == 'error' %}danger{% endif %}" role="alert">{{ message }}</div>
        {% endfor %}
{% endif %}

<div class="contact-from-section mb-150" >
    <div class="container" style="width: 50%;"> 
        <div class="form-title">
            <h4>Complete los datos para proceder con la recuperación</h4>
            
        </div>
        <form action="{% url 'cronometro:correoRecuperacion' %}" class="needs-validation" novalidate="" method="post">
             {% csrf_token %}  
     
                    
                    <a>
                        <label for="correo">Correo electrónico:</label>
                            <input type="email" id="correo" name="correo" class="form-control"  required>
                                                                    
                            </input>
                    </a>
                

                
                    <a>
                        <label for="correoV">Repite el correo electrónico:</label>
                            <input type="email" id="correoV" name="correoV" class="form-control"  required>
                                                                    
                            </input>
                    </a>
                            
       
                    
                        
                   
                            
                

            <div class="modal-footer">
                <button class="btn btn-secondary" type="reset" data-dismiss="modal">Limpiar</button>
                
                <button type="submit" class="btn btn-primary">Enviar correo</button>
            </div>
        </form>    
    </div>
</div>




{% endblock contenedor %}  

cronometro/templates/cronometro/usuario/listado_usuarios.html
{% extends 'cronometro/base/base.html' %}
{% load static %}

{% block titulo %}Listado Usuarios{% endblock titulo %}

{% block encabezado %}Bienbenido{% endblock encabezado %}
{% block subencabezado %}Index{% endblock subencabezado %}

{% block contenedor %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags != 'error' %}{{ message.tags }}{% elif message.tags == 'error' %}danger{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}

{% if request.session.logueoUsuario %}
{% if request.session.logueoUsuario.4 == 'Administrador' %}



<div class="listar-operario mt-50 mb-150 pl-5 pr-5" id="respuesta">
    <div class="contenedor">
        <div class="form-title">
            <h2>Usuarios registrados</h2>
            
        </div>
        <div class="table-responsive">
            <table id="lista" class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Apellidos</th>
                        <th>Email</th>
                        <th>Rol</th>
                        <th>Empresa</th>
                        <th>Estado</th>
                        <th>Opciones</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for usuario in usuarios %}
                    <tr>
                        <td> {{usuario.id}} </td>
                        <td> {{usuario.nombre}}</td>
                        <td> {{usuario.apellido}}</td>
                        <td> {{usuario.email}}</td>
                        <td> {{usuario.rol}}</td>
                        <td> {{usuario.idEmpresa.nombre}} </td>
                        <td> 
                            <a href="{% url  'cronometro:deshabilitarUsuario' usuario.id %}" {% if usuario.estado %}class="btn btn-success"> Habilitado {% else %}class="btn btn-danger"> Deshabilitado {% endif %}</a>
                        </td>
                        <td>
                            <a href="{% url 'cronometro:actualizarUsuario' usuario.id %}" class="btn btn-info">Editar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="pagination-wrap mb-100">
                    <ul  class="pagination">
                        <li><a href="?page=1">&laquo;</a></li>
                        <li><a {% if usuarios.has_previous %} href="?page={{ usuarios.previous_page_number }}" {% endif %}>Anterior</a></li>

                        {% for i in "x"|rjust:usuarios.paginator.num_pages|make_list %}
                        <li><a {% if forloop.counter == usuarios.number %} class="active" {% endif %} href="?page={{ forloop.counter }}"> {{ forloop.counter }} </a></li>
                        {% endfor %}

                        <li><a {% if usuarios.has_next %} href="?page={{usuarios.next_page_number }}" {% endif %}>Siguiente</a></li>
                        <li><a {% if usuarios.has_next %} href="?page={{usuarios.paginator.num_pages }}" {% endif %}>&raquo;</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
No hay datos.
Inicie sesion.
{% endif %}
{% endif %}

{% endblock contenedor %}

cronometro/templates/cronometro/usuario/restablecer_contrasena.html
{% extends 'cronometro/base/base.html' %}
{% load static %}

{% block titulo %}Recuperación de contraseña{% endblock titulo %}

{% block encabezado %}Bienbenido{% endblock encabezado %}
{% block subencabezado %}Index{% endblock subencabezado %}

{% block contenedor %}

{% if messages %}
        {% for message in messages %}
            <div class="alert alert-{% if message.tags != 'error' %}{{ message.tags }}{% elif message.tags == 'error' %}danger{% endif %}" role="alert">{{ message }}</div>
        {% endfor %}
{% endif %}

<div class="contact-from-section mb-150" >
    <div class="container" style="width: 50%;"> 
        <div class="form-title">
            <h2>Ingrese la nueva contraseña</h2>
            
        </div>
        <form action="{% url 'cronometro:formRestablecerContrasena' usuario.id %}" class="needs-validation" novalidate="" method="post">
             {% csrf_token %}  
     
                    
                    <a>
                        <label for="correo">Nueva contraseña:</label>
                            <input type="password" id="password" name="password" class="form-control"  required>
                                                                    
                            </input>
                    </a>
                

                
                    <a>
                        <label for="correo">Repite la nueva contraseña:</label>
                            <input type="password" id="passwordV" name="passwordV" class="form-control"  required>
                                                                    
                            </input>
                    </a>
                            

            <div class="modal-footer">
                <button class="btn btn-secondary" type="reset" data-dismiss="modal">Limpiar</button>
                
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </form>    
    </div>
</div>




{% endblock contenedor %}  